services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    ports:
      - ${WEB_PORT:-8080}-8999:80
    volumes:
      - ./htdocs:/var/www/html
      - ./php/config/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:9.3.0
    volumes:
      - ./mysql/db_volume:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ${MYSQL_DATABASE:-my_database}
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    ports:
      - 10000-11000:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: ""
    depends_on:
      - mysql
    restart: unless-stopped
